apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: inventory-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inventory-quarkus
    app.kubernetes.io/part-of: stephanie-app
  name: inventory-quarkus
  namespace: yangcao
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: inventory-quarkus
status:
  loadBalancer: {}
